version: '3.0'
services:
  haste-server:
    build: .
    environment:
     - STORAGE_TYPE=file
     - STORAGE_FILEPATH=data
    ports:
     - 80:7777
    volumes:
      - ./data:/usr/src/app/data
    user: "$DOCKER_USER"
